# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e409c0656dc499a2bc084879667d17e220a5d280f774b51993038d5862c39d32db8317b52c57ab552eb4c066cf5bcb774799e6be8120487deb1f96443e92821

test:
  secret_key_base: 61ce2cf794e01cfa3a526e9faf4d5d282f67994d53da083ca532c595c02880ce1075163099b1572b2edd34ccb7537f265247aabace87e284cc0bc7963523885e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
